# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

version: 2
updates:
    - package-ecosystem: "github-actions"
      open-pull-requests-limit: 40
      directory: "/"
      labels:
          - "🤖 Dependencies"
      schedule:
          interval: "daily"

    # gomod split by alphabet ranges to reduce group PR size
    # a-d ~11 modules | e-n ~12 modules | o-z ~12 modules
    - package-ecosystem: "gomod"
      open-pull-requests-limit: 15
      allow:
          - dependency-type: "all"
      directories:
          - "/a*"
          - "/b*"
          - "/c*"
          - "/d*"
      labels:
          - "🤖 Dependencies"
      schedule:
          interval: "daily"
      groups:
          testcontainers-modules:
              patterns:
                  - "github.com/testcontainers/testcontainers-go"
                  - "github.com/testcontainers/testcontainers-go/modules/**"
          utils-modules:
              patterns:
                  - "github.com/gofiber/utils"
                  - "github.com/gofiber/utils/**"
          fiber-modules:
              patterns:
                  - "github.com/gofiber/fiber/**"
          fasthttp-modules:
              patterns:
                  - "github.com/valyala/fasthttp"
                  - "github.com/valyala/fasthttp/**"
          golang-modules:
              patterns:
                  - "golang.org/x/**"
          aws-modules:
              patterns:
                  - "github.com/aws/**"
          azure-modules:
              patterns:
                  - "github.com/Azure/**"
          ebitengine-modules:
              patterns:
                  - "github.com/ebitengine/**"
          go-logr-modules:
              patterns:
                  - "github.com/go-logr/**"
          logrus-modules:
              patterns:
                  - "github.com/sirupsen/logrus"
                  - "github.com/sirupsen/logrus/**"
          go-ole-modules:
              patterns:
                  - "github.com/go-ole/**"
          go-redis-modules:
              patterns:
                  - "github.com/redis/go-redis/**"
          grpc-gateway-modules:
              patterns:
                  - "github.com/grpc-ecosystem/grpc-gateway/**"
          shirou-modules:
              patterns:
                  - "github.com/shirou/gopsutil"
                  - "github.com/shirou/gopsutil/**"
          morikuni-modules:
              patterns:
                  - "github.com/morikuni/**"
          klauspost-modules:
              patterns:
                  - "github.com/klauspost/**"
          snappy-modules:
              patterns:
                  - "github.com/golang/snappy"
          tklauser-modules:
              patterns:
                  - "github.com/tklauser/**"
          docker-modules:
              patterns:
                  - "github.com/docker/**"
                  - "github.com/containerd/**"
                  - "github.com/distribution/**"
                  - "github.com/moby/**"
          google-modules:
              patterns:
                  - "google.golang.org/**"
          opentelemetry-modules:
              patterns:
                  - "go.opentelemetry.io/**"
          testify-modules:
              patterns:
                  - "github.com/stretchr/testify"

    - package-ecosystem: "gomod"
      open-pull-requests-limit: 15
      allow:
          - dependency-type: "all"
      directories:
          - "/e*"
          - "/f*"
          - "/g*"
          - "/h*"
          - "/i*"
          - "/j*"
          - "/k*"
          - "/l*"
          - "/m*"
          - "/n*"
      labels:
          - "🤖 Dependencies"
      schedule:
          interval: "daily"
      groups:
          testcontainers-modules:
              patterns:
                  - "github.com/testcontainers/testcontainers-go"
                  - "github.com/testcontainers/testcontainers-go/modules/**"
          utils-modules:
              patterns:
                  - "github.com/gofiber/utils"
                  - "github.com/gofiber/utils/**"
          fiber-modules:
              patterns:
                  - "github.com/gofiber/fiber/**"
          fasthttp-modules:
              patterns:
                  - "github.com/valyala/fasthttp"
                  - "github.com/valyala/fasthttp/**"
          golang-modules:
              patterns:
                  - "golang.org/x/**"
          aws-modules:
              patterns:
                  - "github.com/aws/**"
          azure-modules:
              patterns:
                  - "github.com/Azure/**"
          ebitengine-modules:
              patterns:
                  - "github.com/ebitengine/**"
          go-logr-modules:
              patterns:
                  - "github.com/go-logr/**"
          logrus-modules:
              patterns:
                  - "github.com/sirupsen/logrus"
                  - "github.com/sirupsen/logrus/**"
          go-ole-modules:
              patterns:
                  - "github.com/go-ole/**"
          go-redis-modules:
              patterns:
                  - "github.com/redis/go-redis/**"
          grpc-gateway-modules:
              patterns:
                  - "github.com/grpc-ecosystem/grpc-gateway/**"
          shirou-modules:
              patterns:
                  - "github.com/shirou/gopsutil"
                  - "github.com/shirou/gopsutil/**"
          morikuni-modules:
              patterns:
                  - "github.com/morikuni/**"
          klauspost-modules:
              patterns:
                  - "github.com/klauspost/**"
          snappy-modules:
              patterns:
                  - "github.com/golang/snappy"
          tklauser-modules:
              patterns:
                  - "github.com/tklauser/**"
          docker-modules:
              patterns:
                  - "github.com/docker/**"
                  - "github.com/containerd/**"
                  - "github.com/distribution/**"
                  - "github.com/moby/**"
          google-modules:
              patterns:
                  - "google.golang.org/**"
          opentelemetry-modules:
              patterns:
                  - "go.opentelemetry.io/**"
          testify-modules:
              patterns:
                  - "github.com/stretchr/testify"

    - package-ecosystem: "gomod"
      open-pull-requests-limit: 15
      allow:
          - dependency-type: "all"
      directories:
          - "/o*"
          - "/p*"
          - "/q*"
          - "/r*"
          - "/s*"
          - "/t*"
          - "/t*/*"
          - "/u*"
          - "/v*"
          - "/w*"
          - "/x*"
          - "/y*"
          - "/z*"
      labels:
          - "🤖 Dependencies"
      schedule:
          interval: "daily"
      groups:
          testcontainers-modules:
              patterns:
                  - "github.com/testcontainers/testcontainers-go"
                  - "github.com/testcontainers/testcontainers-go/modules/**"
          utils-modules:
              patterns:
                  - "github.com/gofiber/utils"
                  - "github.com/gofiber/utils/**"
          fiber-modules:
              patterns:
                  - "github.com/gofiber/fiber/**"
          fasthttp-modules:
              patterns:
                  - "github.com/valyala/fasthttp"
                  - "github.com/valyala/fasthttp/**"
          golang-modules:
              patterns:
                  - "golang.org/x/**"
          aws-modules:
              patterns:
                  - "github.com/aws/**"
          azure-modules:
              patterns:
                  - "github.com/Azure/**"
          ebitengine-modules:
              patterns:
                  - "github.com/ebitengine/**"
          go-logr-modules:
              patterns:
                  - "github.com/go-logr/**"
          logrus-modules:
              patterns:
                  - "github.com/sirupsen/logrus"
                  - "github.com/sirupsen/logrus/**"
          go-ole-modules:
              patterns:
                  - "github.com/go-ole/**"
          go-redis-modules:
              patterns:
                  - "github.com/redis/go-redis/**"
          grpc-gateway-modules:
              patterns:
                  - "github.com/grpc-ecosystem/grpc-gateway/**"
          shirou-modules:
              patterns:
                  - "github.com/shirou/gopsutil"
                  - "github.com/shirou/gopsutil/**"
          morikuni-modules:
              patterns:
                  - "github.com/morikuni/**"
          klauspost-modules:
              patterns:
                  - "github.com/klauspost/**"
          snappy-modules:
              patterns:
                  - "github.com/golang/snappy"
          tklauser-modules:
              patterns:
                  - "github.com/tklauser/**"
          docker-modules:
              patterns:
                  - "github.com/docker/**"
                  - "github.com/containerd/**"
                  - "github.com/distribution/**"
                  - "github.com/moby/**"
          google-modules:
              patterns:
                  - "google.golang.org/**"
          opentelemetry-modules:
              patterns:
                  - "go.opentelemetry.io/**"
          testify-modules:
              patterns:
                  - "github.com/stretchr/testify"
