name-template: 'Cassandra - v$RESOLVED_VERSION'
tag-template: 'cassandra/v$RESOLVED_VERSION'
tag-prefix: cassandra/v
include-paths:
  - cassandra
categories:
    - title: '🚀 New'
      labels:
          - '✏️ Feature'
    - title: '🧹 Updates'
      labels:
          - '🧹 Updates'
          - '🤖 Dependencies'
    - title: '🐛 Fixes'
      labels:
          - '☢️ Bug'
    - title: '📚 Documentation'
      labels:
          - '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
            - '✏️ Feature'
    patch:
        labels:
            - 'patch'
            - '📒 Documentation'
            - '☢️ Bug'
            - '🤖 Dependencies'
            - '🧹 Updates'
    default: patch
template: |
    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...cassandra/v$RESOLVED_VERSION

    Thank you $CONTRIBUTORS for making this update possible.
