// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package objectbox

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type cache_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var CacheBinding = cache_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 8543848339172790713,
}

// Cache_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Cache_ = struct {
	Id        *objectbox.PropertyUint64
	Key       *objectbox.PropertyString
	Value     *objectbox.PropertyByteVector
	ExpiresAt *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &CacheBinding.Entity,
		},
	},
	Key: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &CacheBinding.Entity,
		},
	},
	Value: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &CacheBinding.Entity,
		},
	},
	ExpiresAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &CacheBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (cache_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (cache_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Cache", 1, 8543848339172790713)
	model.Property("Id", 6, 1, 3986202391135829849)
	model.PropertyFlags(1)
	model.Property("Key", 9, 2, 6255868849552810122)
	model.PropertyFlags(2080)
	model.PropertyIndex(1, 4154314791709387436)
	model.Property("Value", 23, 3, 441219408181596061)
	model.Property("ExpiresAt", 10, 4, 6145573473554079304)
	model.PropertyFlags(8)
	model.PropertyIndex(2, 8378671756205806266)
	model.EntityLastPropertyId(4, 6145573473554079304)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (cache_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Cache).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (cache_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Cache).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (cache_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (cache_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Cache)
	var offsetKey = fbutils.CreateStringOffset(fbb, obj.Key)
	var offsetValue = fbutils.CreateByteVectorOffset(fbb, obj.Value)

	// build the FlatBuffers object
	fbb.StartObject(4)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetKey)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetValue)
	fbutils.SetInt64Slot(fbb, 3, obj.ExpiresAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (cache_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Cache' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &Cache{
		Id:        propId,
		Key:       fbutils.GetStringSlot(table, 6),
		Value:     fbutils.GetByteVectorSlot(table, 8),
		ExpiresAt: fbutils.GetInt64Slot(table, 10),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (cache_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Cache, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (cache_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Cache), nil)
	}
	return append(slice.([]*Cache), object.(*Cache))
}

// Box provides CRUD access to Cache objects
type CacheBox struct {
	*objectbox.Box
}

// BoxForCache opens a box of Cache objects
func BoxForCache(ob *objectbox.ObjectBox) *CacheBox {
	return &CacheBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Cache.Id property on the passed object will be assigned the new ID as well.
func (box *CacheBox) Put(object *Cache) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Cache.Id property on the passed object will be assigned the new ID as well.
func (box *CacheBox) Insert(object *Cache) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *CacheBox) Update(object *Cache) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *CacheBox) PutAsync(object *Cache) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Cache.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Cache.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *CacheBox) PutMany(objects []*Cache) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *CacheBox) Get(id uint64) (*Cache, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Cache), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *CacheBox) GetMany(ids ...uint64) ([]*Cache, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Cache), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *CacheBox) GetManyExisting(ids ...uint64) ([]*Cache, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Cache), nil
}

// GetAll reads all stored objects
func (box *CacheBox) GetAll() ([]*Cache, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Cache), nil
}

// Remove deletes a single object
func (box *CacheBox) Remove(object *Cache) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *CacheBox) RemoveMany(objects ...*Cache) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Cache_ struct to create conditions.
// Keep the *CacheQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *CacheBox) Query(conditions ...objectbox.Condition) *CacheQuery {
	return &CacheQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Cache_ struct to create conditions.
// Keep the *CacheQuery if you intend to execute the query multiple times.
func (box *CacheBox) QueryOrError(conditions ...objectbox.Condition) (*CacheQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &CacheQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See CacheAsyncBox for more information.
func (box *CacheBox) Async() *CacheAsyncBox {
	return &CacheAsyncBox{AsyncBox: box.Box.Async()}
}

// CacheAsyncBox provides asynchronous operations on Cache objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type CacheAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForCache creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use CacheBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForCache(ob *objectbox.ObjectBox, timeoutMs uint64) *CacheAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &CacheAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *CacheAsyncBox) Put(object *Cache) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *CacheAsyncBox) Insert(object *Cache) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *CacheAsyncBox) Update(object *Cache) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *CacheAsyncBox) Remove(object *Cache) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Cache which Id is either 42 or 47:
//
// box.Query(Cache_.Id.In(42, 47)).Find()
type CacheQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *CacheQuery) Find() ([]*Cache, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Cache), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *CacheQuery) Offset(offset uint64) *CacheQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *CacheQuery) Limit(limit uint64) *CacheQuery {
	query.Query.Limit(limit)
	return query
}
