name: After Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - gofiber/recipes
    steps:
      - uses: gofiber/.github/.github/actions/trigger-dependabot@main
        with:
          repo: ${{ matrix.repo }}
          reason: 'storage ${{ github.event.release.tag_name }} released'
          token: ${{ secrets.DISPATCH_TOKEN }}
