name: Linter

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    uses: gofiber/.github/.github/workflows/go-lint.yml@main
    with:
      repo-type: multi
      golangci-lint-args: "--tests=false --timeout=5m"
