name: Release Drafter Cassandra 
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'cassandra/**'
jobs:
    draft_release_cassandra:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-cassandra.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
