on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - "pebble/**"
  workflow_dispatch:
name: "Tests pebble"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '${{ matrix.go-version }}'
          cache-dependency-path: pebble/go.sum
      - name: Test Pebble
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./pebble
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
