name: Tests CloudflareKV
on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - 'cloudflarekv/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: cloudflarekv/go.sum
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
      - name: Start Wrangler Dev
        run: |
          .github/scripts/initialize-wrangler.sh
          cd cloudflarekv && npx wrangler dev &
          npx wait-on tcp:8787
      - name: Run Go Tests
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: cloudflarekv
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
