on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - 'valkey/**'
      - '.github/workflows/test-valkey.yml'
  workflow_dispatch:
name: "Tests Valkey"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
        valkey:
          - '7'
          - '8'
    steps:
      - name: Fetch Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup Valkey Cluster
        uses: vishnudxb/redis-cluster@e29c352fa58527003afc982e96db437c0c49e6aa # 1.10.0
        with:
          master1-port: 7000
          master2-port: 7001
          master3-port: 7002
          slave1-port: 7003
          slave2-port: 7004
          slave3-port: 7005
          sleep-duration: 10
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '${{ matrix.go-version }}'
          cache-dependency-path: valkey/go.sum
      - name: Run Test
        env:
          TEST_VALKEY_IMAGE: "public.ecr.aws/valkey/valkey:${{ matrix.valkey }}"
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./valkey
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
