on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - 'postgres/**'
  workflow_dispatch:
name: "Tests Postgres"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '${{ matrix.go-version }}'
          cache-dependency-path: postgres/go.sum
      - name: Run Test
        env:
          TEST_POSTGRES_IMAGE: "public.ecr.aws/docker/library/postgres:16-alpine"
          TEST_COCKROACHDB_IMAGE: "cockroachdb/cockroach:latest-v23.2"
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./postgres
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
