on:
    push:
        branches:
            - master
            - main
        paths:
            - 'azureblob/**'
    pull_request:
        paths:
            - 'azureblob/**'
name: "Tests Azure Blob"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.23.x
                    - 1.24.x
        steps:
        -   name: Fetch Repository
            uses: actions/checkout@v4
        -   name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: '${{ matrix.go-version }}'
        -   name: Run Test
            env:
                TEST_AZURITE_IMAGE: mcr.microsoft.com/azure-storage/azurite:latest
            run: cd ./azureblob && go test ./... -v -race
