on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - 'badger/**'
  workflow_dispatch:
name: "Tests Badger"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '${{ matrix.go-version }}'
          cache-dependency-path: badger/go.sum
      - name: Test Badger
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./badger
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
