on:
  push:
    branches:
      - master
      - main
    paths:
      - 'scylladb/**'
  pull_request:
    paths:
      - 'scylladb/**'
  workflow_dispatch:
name: "Tests ScyllaDb"

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        env:
          TEST_SCYLLADB_IMAGE: "scylladb/scylla:6.2"
        run: cd ./scylladb && go test ./... -v -race
