on:
  push:
    branches:
      - master
      - main
    paths:
      - 'surrealdb/**'
  pull_request:
    paths:
      - 'surrealdb/**'
  workflow_dispatch:
name: "Tests SurrealDB"

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        env:
          TEST_SURREALDB_IMAGE: surrealdb/surrealdb:latest
        run: cd ./surrealdb && go test ./... -v -race
