'on':
  - push
  - pull_request
name: Local Storage
jobs:
  Tests:
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x         
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Test Badger
        run: cd ./badger && go test ./... -v -race
      - name: Test Memory
        run: cd ./memory && go test ./... -v -race
      - name: Test SQLite3
        run: cd ./sqlite3 && go test ./... -v -race
