on:
  push:
    branches:
      - master
      - main
    paths:
      - 'testhelpers/redis/**'
  pull_request:
    paths:
      - 'testhelpers/redis/**'
  workflow_dispatch:
name: "Tests TestHelper Redis"

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
        redis:
          - '7'
          - '8'
    steps:
      - name: Fetch Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        env:
          TEST_REDIS_IMAGE: "docker.io/redis:${{ matrix.redis }}"
        working-directory: testhelpers/redis
        run: go test ./... -v -race
