on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - "firestore/**"
name: "Tests Firestore"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "${{ matrix.go-version }}"
          cache-dependency-path: firestore/go.sum
      - name: Run Test
        env:
          TEST_FIRESTORE_IMAGE: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./firestore
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
